import os
import argparse
import sys
import re
from datetime import datetime
from dotenv import load_dotenv

# Add src to python path if needed (although relative imports will work)
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from src.parser import split_markdown
from src.metadata import extract_metadata
from src.linker import cross_link_concepts
from src.indexer import write_okf_bundle

def main():
    # Load .env file
    load_dotenv()
    
    parser = argparse.ArgumentParser(
        description="OKF Compiler: Transform flat Markdown files into structured, cross-linked Open Knowledge Format bundles."
    )
    parser.add_argument(
        "--input", "-i",
        required=True,
        help="Path to the input flat markdown file (e.g., generated by Marker)"
    )
    parser.add_argument(
        "--output-dir", "-o",
        default=".okf",
        help="Directory where the OKF bundle will be created (default: .okf)"
    )
    parser.add_argument(
        "--split-level", "-s",
        default="##",
        help="Header prefix to split the document at (default: '##')"
    )
    
    args = parser.parse_args()
    
    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' does not exist.", file=sys.stderr)
        sys.exit(1)
        
    print(f"Loading input file: {args.input}")
    with open(args.input, "r", encoding="utf-8") as f:
        file_content = f.read()
        
    print(f"Splitting document using level marker: '{args.split_level}'")
    chunks = split_markdown(file_content, args.split_level)
    print(f"Identified {len(chunks)} document chunks.")
    
    # Check for API Key, otherwise warn and run in fallback heuristic mode
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("\n[WARNING] GEMINI_API_KEY environment variable is not set!")
        print("The compiler will run in heuristic fallback mode (no LLM calls).")
        print("To resolve, set GEMINI_API_KEY in a .env file or your environment.\n")
        
    concepts = {}
    
    for idx, chunk in enumerate(chunks, 1):
        header = chunk["header"]
        content = chunk["content"]
        
        print(f"Processing chunk {idx}/{len(chunks)}: '{header}'...")
        
        meta = None
        cleaned_content = content
        
        if api_key:
            try:
                meta, cleaned_content = extract_metadata(content)
                print(f"  -> Extracted metadata successfully (Type: {meta['type']})")
            except Exception as e:
                print(f"  -> [LLM Error] Failed to generate metadata via Gemini: {e}")
                print("  -> Falling back to heuristic metadata...")
                
        # Heuristic Fallback
        if not meta:
            # Generate a slug from the header
            slug = re.sub(r'[^a-z0-9\-]', '', header.lower().replace(' ', '-').replace('_', '-'))
            slug = slug.strip('-')
            if not slug:
                slug = f"concept-{idx}"
                
            # Basic OKF-compliant fallback dictionary
            meta = {
                "type": "concept",
                "title": header,
                "description": f"Section covering: {header}.",
                "tags": ["uncategorized"],
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "filename": slug
            }
            cleaned_content = content
            print(f"  -> Created heuristic fallback (Filename: {meta['filename']})")
            
        concepts[f"chunk_{idx}"] = {
            "metadata": meta,
            "content": cleaned_content
        }
        
    print("\nRunning semantic cross-linker...")
    linked_contents = cross_link_concepts(concepts)
    
    print(f"Writing OKF bundle to: {args.output_dir}")
    write_okf_bundle(args.output_dir, concepts, linked_contents)
    
    print("\n[SUCCESS] Compilation complete!")
    print(f"Created OKF bundle in folder: {os.path.abspath(args.output_dir)}")
    print(f"Index catalog: {os.path.join(args.output_dir, 'index.md')}")

if __name__ == "__main__":
    main()
